INSERT INTO keywords (word, points, size) VALUES
-- 20 palavras 'large' (20 pontos)
('Consultoria Empresarial', 20, 'large'),
('Desenvolvimento Pessoal', 20, 'large'),
('Impacto Social', 20, 'large'),
('Transformação', 20, 'large'),
('Protagonismo', 20, 'large'),
('Capacitação', 20, 'large'),
('Projetos Reais', 20, 'large'),
('Vivência Empresarial', 20, 'large'),
('Gestão Colaborativa', 20, 'large'),
('Cultura Empreendedora', 20, 'large'),
('Liderança Jovem', 20, 'large'),
('Inovação Social', 20, 'large'),
('Movimento Nacional', 20, 'large'),
('Rede de Impacto', 20, 'large'),
('Empreendedorismo Jovem', 20, 'large'),
('Desenvolvimento Regional', 20, 'large'),
('Engajamento Social', 20, 'large'),
('Responsabilidade Social', 20, 'large'),
('Crescimento Profissional', 20, 'large'),
('Formação de Líderes', 20, 'large'),
-- 15 palavras 'medium' (35 pontos)
('Brasil Júnior', 35, 'medium'),
('FEJEPE', 35, 'medium'),
('Junior Enterprise', 35, 'medium'),
('Networking', 35, 'medium'),
('Mentoria', 35, 'medium'),
('Benchmarking', 35, 'medium'),
('Cocriação', 35, 'medium'),
('Colaboração', 35, 'medium'),
('Ética', 35, 'medium'),
('Diversidade', 35, 'medium'),
('Inclusão', 35, 'medium'),
('Competitividade', 35, 'medium'),
('Educação Empreendedora', 35, 'medium'),
('Desafio Empreendedor', 35, 'medium'),
('Movimento Empresa Júnior', 35, 'medium'),
-- 12 palavras 'small' (50 pontos)
('Seed a Bit', 50, 'small'),
('Liderança', 50, 'small'),
('Empatia', 50, 'small'),
('Visão', 50, 'small'),
('Missão', 50, 'small'),
('Valores', 50, 'small'),
('Propósito', 50, 'small'),
('Excelência', 50, 'small'),
('Resultados', 50, 'small'),
('Crescimento', 50, 'small'),
('Iniciativa', 50, 'small'),
('Comprometimento', 50, 'small');